### ISSUE TITLE
Initial Setup

### ISSUE THREAD

**Issue by MelSumner** [ember-components/ember-component-patterns#1]
Setup this repo: 

1. [x] add basic addons that are always added
2. [x] add `broccoli-static-site-json` addon & do initial setup
3. [x] do initial app setup (basic styles, main routes, etc)
4. [x] write issues to coordinate the work
5. [x] update readme to describe what's going on in the repo and how to contribute

**Comment by hergaiety** [comment]
```bash
gaiety@friller:~/w/ember-component-patterns|main✓
➤ ember s
Directory not found: /home/gaiety/web/ember-component-patterns/content
```


There's no content dir in the repo, perhaps was this not pushed up or are there additional steps I need to do?

**Comment by MelSumner** [comment]
@hergaiety yes, a content folder needs to be added to the root directory, sorry about that! let me see if I have an unpushed branch that already has this.
