### ISSUE TITLE
Add linkable header component

### ISSUE THREAD

**Issue by hergaiety** [ember-components/ember-component-patterns#13]
![Screenshot_2020-12-09_08-27-25](https://user-images.githubusercontent.com/1664093/101642339-7efb4080-39f8-11eb-97ec-0b8791886dab.png)

Like the previous site (https://emberjs-1.gitbook.io/ember-component-patterns/) users should be able to focus on or hover over a header to see a link icon. Clicking it should navigate to an anchor link tied to the same headline.

This will be a very common thing throughout the app so we may wish to make a simple component for this.

**Comment by mattfrankjames** [comment]
I have submitted a [PR](https://github.com/ember-components/ember-component-patterns/pull/15) for this.

**Comment by hergaiety** [comment]
Thanks @mattfrankjames for knocking this out! https://github.com/ember-components/ember-component-patterns/pull/15
Tiny FYI, in the future these issues can be autoclosed by including `resolves #13` for example in the PR description. I'll happily close this manually, cheers~!
