### ISSUE TITLE
Create base styles for app

### ISSUE THREAD

**Issue by MelSumner** [ember-components/ember-component-patterns#2]
## Summary
Create the base CSS styling for the app. 

## Acceptance Criteria
- "mobile-first" responsive CSS
- keep the current styling approach (`ember-cli-sass`) 
- CSS must be easily maintainable (not too many abstractions/mixins)
- styles must meet WCAG AA success criteria (esp regarding color-contrast)
- grid CSS or flexbox CSS is fine; table-based layouts are not fine

**Comment by mattfrankjames** [comment]
I have a [PR](https://github.com/ember-components/ember-component-patterns/pull/17) for this.

**Comment by mattfrankjames** [comment]
This [PR](https://github.com/ember-components/ember-component-patterns/pull/17) was merged on Friday and resolves this issue.
