### ISSUE TITLE
Add homepage content

### ISSUE THREAD

**Issue by MelSumner** [ember-components/ember-component-patterns#7]
## Summary
Convert the gitbook homepage content into the app's homepage content

## Acceptance Criteria
- Add content on https://emberjs-1.gitbook.io/ember-component-patterns/ to the app's index.hbs template (create it if it does not already exist)
- Ensure that semantic HTML (markup) is used
- Ensure that the content renders correctly in the browser before submitting the PR
- Include screenshot in PR

**Comment by hergaiety** [comment]
I can jump onto this. I'd love to see the site ready for translation from the beginning, so I'm thinking I'll do this with `ember-intl`.
